# Generated by Django 4.1.7 on 2023-03-26 20:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Customers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userName', models.CharField(max_length=200, verbose_name='User Name')),
                ('email', models.EmailField(max_length=200, verbose_name='E-Mail')),
                ('phoneNumber', models.CharField(max_length=50, verbose_name='Phone Number')),
                ('note', models.CharField(blank=True, max_length=200, verbose_name='Note')),
            ],
        ),
        migrations.CreateModel(
            name='Suppliers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Supplier Name')),
                ('email', models.EmailField(max_length=200, verbose_name='E-Mail')),
                ('phoneNumber', models.CharField(max_length=50, verbose_name='Phone Number')),
                ('note', models.CharField(blank=True, max_length=200, verbose_name='Note')),
            ],
        ),
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('productName', models.CharField(max_length=200, verbose_name='Product Name')),
                ('upc', models.IntegerField(verbose_name='UPC')),
                ('price', models.DecimalField(decimal_places=2, max_digits=6, verbose_name='Price Per Unit')),
                ('amount', models.IntegerField(default=0, verbose_name='Amount')),
                ('description', models.CharField(blank=True, max_length=200, verbose_name='Description')),
                ('supplierID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.suppliers', verbose_name='Supplier ID')),
            ],
        ),
        migrations.CreateModel(
            name='Orders',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.IntegerField(verbose_name='Amount')),
                ('date', models.DateTimeField(verbose_name='Date and Time')),
                ('shortnote', models.CharField(blank=True, max_length=20, verbose_name='Short Note')),
                ('note', models.CharField(blank=True, max_length=200, verbose_name='Note')),
                ('price', models.DecimalField(decimal_places=2, max_digits=6)),
                ('customerId', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.customers', verbose_name='Customer ID')),
                ('stockID', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.stock', verbose_name='Stock ID')),
                ('userId', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Authorizer ID')),
            ],
        ),
        migrations.CreateModel(
            name='Incoming',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.IntegerField(verbose_name='Amount')),
                ('date', models.DateTimeField(verbose_name='Date and Time')),
                ('shortnote', models.CharField(blank=True, max_length=20, verbose_name='Short Note')),
                ('note', models.CharField(blank=True, max_length=200, verbose_name='Note')),
                ('price', models.DecimalField(decimal_places=2, max_digits=6)),
                ('stockID', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.stock', verbose_name='Stock ID')),
                ('supplierId', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.suppliers', verbose_name='Supplier ID')),
                ('userId', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Authorizer ID')),
            ],
        ),
    ]
