# Generated by Django 4.1.7 on 2023-02-26 00:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stock',
            name='number',
        ),
        migrations.AddField(
            model_name='stock',
            name='amount',
            field=models.IntegerField(default=0, verbose_name='Amount'),
        ),
        migrations.AlterField(
            model_name='customers',
            name='email',
            field=models.EmailField(max_length=200, verbose_name='E-Mail'),
        ),
        migrations.AlterField(
            model_name='customers',
            name='note',
            field=models.CharField(max_length=200, verbose_name='Note'),
        ),
        migrations.AlterField(
            model_name='customers',
            name='phoneNumber',
            field=models.CharField(max_length=50, verbose_name='Phone Number'),
        ),
        migrations.AlterField(
            model_name='customers',
            name='userName',
            field=models.CharField(max_length=200, verbose_name='User Name'),
        ),
        migrations.AlterField(
            model_name='orders',
            name='amount',
            field=models.IntegerField(verbose_name='Amount'),
        ),
        migrations.AlterField(
            model_name='orders',
            name='customerId',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.customers', verbose_name='Customer ID'),
        ),
        migrations.AlterField(
            model_name='orders',
            name='date',
            field=models.DateTimeField(verbose_name='Date and Time'),
        ),
        migrations.AlterField(
            model_name='orders',
            name='note',
            field=models.CharField(max_length=200, verbose_name='Note'),
        ),
        migrations.AlterField(
            model_name='orders',
            name='shortnote',
            field=models.CharField(max_length=20, verbose_name='Short Note'),
        ),
        migrations.AlterField(
            model_name='orders',
            name='stockID',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.stock', verbose_name='Stock ID'),
        ),
        migrations.AlterField(
            model_name='orders',
            name='userId',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Authorizer ID'),
        ),
        migrations.AlterField(
            model_name='stock',
            name='description',
            field=models.CharField(max_length=200, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='stock',
            name='productName',
            field=models.CharField(max_length=200, verbose_name='Product Name'),
        ),
        migrations.AlterField(
            model_name='stock',
            name='supplierID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.suppliers', verbose_name='Supplier ID'),
        ),
        migrations.AlterField(
            model_name='stock',
            name='upc',
            field=models.IntegerField(verbose_name='UPC'),
        ),
        migrations.AlterField(
            model_name='suppliers',
            name='email',
            field=models.EmailField(max_length=200, verbose_name='E-Mail'),
        ),
        migrations.AlterField(
            model_name='suppliers',
            name='name',
            field=models.CharField(max_length=200, verbose_name='Supplier Name'),
        ),
        migrations.AlterField(
            model_name='suppliers',
            name='note',
            field=models.CharField(max_length=200, verbose_name='Note'),
        ),
        migrations.AlterField(
            model_name='suppliers',
            name='phoneNumber',
            field=models.CharField(max_length=50, verbose_name='Phone Number'),
        ),
        migrations.CreateModel(
            name='Incoming',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.IntegerField(verbose_name='Amount')),
                ('date', models.DateTimeField(verbose_name='Date and Time')),
                ('shortnote', models.CharField(max_length=20, verbose_name='Short Note')),
                ('note', models.CharField(max_length=200, verbose_name='Note')),
                ('cents', models.IntegerField()),
                ('stockID', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.stock', verbose_name='Stock ID')),
                ('supplierId', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.suppliers', verbose_name='Supplier ID')),
                ('userId', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Authorizer ID')),
            ],
        ),
    ]
